In [53]:
lst1 = [10, 20, 30, 40, 50]
lst2 = [2, 2, 2, 2, 2]


vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado: ")
print(vctr1)
print(vctr2)

vctr_dot = vctr1.dot(vctr2)

print("Resultado: ")
print(vctr_dot)

Vector creado: 
[10 20 30 40 50]
[2 2 2 2 2]
Resultado: 
300


In [52]:
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 1, 1, 1, 1]


vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado: ")
print(vctr1)
print(vctr2)

vctr_dot = vctr1.dot(vctr2)

print("Resultado: ")
print(vctr_dot)

Vector creado: 
[10 20 30 40 50]
[1 1 1 1 1]
Resultado: 
150


In [51]:
lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 2, 3, 4, 5]


vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado: ")
print(vctr1)
print(vctr2)

vctr_add = vctr1 - vctr2
vctr_add2 = vctr1 * vctr2
vctr_add3 = vctr1 / vctr2

print("Resultado: ")
print(vctr_add)
print(vctr_add2)
print(vctr_add3)

Vector creado: 
[10 20 30 40 50]
[1 2 3 4 5]
Resultado: 
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [45]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [10, 20, 30, 40, 50, 60, 70]


vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado: ")
print(vctr1)
print(vctr2)

vctr_add = vctr1 + vctr2

print("Resultado: ")
print(vctr_add)

Vector creado: 
[1 2 3 4 5]
[10 20 30 40 50 60 70]


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [46]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [10, 20, 30, 40, 50]


vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado: ")
print(vctr1)
print(vctr2)

vctr_add = vctr1 + vctr2

print("Resultado: ")
print(vctr_add)

Vector creado: 
[1 2 3 4 5]
[10 20 30 40 50]
Resultado: 
[11 22 33 44 55]


In [39]:
import numpy as np

lst = [[1], [2], [3]]
Nomb = [["Juan"], ["Carolina"], ["Andres"]]
cedu = [["111111"], ["222222"], ["333333"]]

vctr = np.array(lst)
vctr2 = np.array(Nomb)
vctr3 = np.array(cedu)

print("Vector creado: ")
print(vctr)
print(vctr2)
print(vctr3)

Vector creado: 
[[1]
 [2]
 [3]]
[['Juan']
 ['Carolina']
 ['Andres']]
[['111111']
 ['222222']
 ['333333']]


In [35]:
import numpy as np

lst = [1,2,3,4,5]
Nomb = ["Juan", "Carolina", "Andres", "Laura", "Jefry"]
cedu = ["111111", "222222", "333333", "444444", "555555"]

vctr = np.array(lst)
vctr2 = np.array(Nomb)
vctr3 = np.array(cedu)

print("Vector creado: ")
print(vctr)
print(vctr2)
print(vctr3)

Vector creado: 
[1 2 3 4 5]
['Juan' 'Carolina' 'Andres' 'Laura' 'Jefry']
['111111' '222222' '333333' '444444' '555555']


In [36]:
# Asignación Lista
Nombres = []
Cedulas = []
Direcciones = []
Tamaño = 3

for i in range(Tamaño):
    print("Registro número:", i+1)
    nombre = input("Nombre: ")
    cedula = input("Cédula: ")
    direccion = input("Dirección: ")

    # Agregar a las listas
    Nombres.append(nombre)
    Cedulas.append(cedula)
    Direcciones.append(direccion)

print("\n--- Resultados ---")
print("Nombres:", Nombres)
print("Cédulas:", Cedulas)
print("Direcciones:", Direcciones)


Registro número: 1


KeyboardInterrupt: Interrupted by user

In [13]:
#Asiganacion Lista
Nombres = ["Juan", "Carolina", "Andres", "Laura", "Jefry"]

#Lista 2 Cedulas
Cedulas = ["111111", "222222", "333333", "444444", "555555"]

#Imprimir Valor
indice = 0

while indice < len(Nombres):
    print(Nombres[indice] , Cedulas [indice])
    indice += 1

Juan 111111
Carolina 222222
Andres 333333
Laura 444444
Jefry 555555


In [8]:
#Asiganacion Lista
Nombres = ["Juan", "Carolina", "Andres", "Laura", "Jefry"]

#Remueve Variable de Lista
Nombres.remove("Juan")
Nombres.remove("Jefry")

#Imprimir
print(Nombres)

['Carolina', 'Andres', 'Laura']


In [ ]:
Nombres = ["Juan", "Carolina", "Andres", "Laura", "Jefry"]

Nombres.pop(1)
Nombres.pop(-1)

print(Nombres)

['Juan', 'Andres', 'Laura']


In [ ]:
Lista=["ejemplo1","ejemplo2","ejemplo3"]
Print("1"())

(1, 'ejemplo', 2, 3, 2, 1)


In [ ]:
mylist = ["Familia","Furbol"]
print("Mis Cosas Favoritas", mylist)

Mis Cosas Favoritas ['Familia', 'Furbol']


In [ ]:
print("mis cosas Favoritas")
for Item in mylist:
    print(Item)

mis cosas Favoritas
Familia
Furbol
