In [ ]:
# importar numpy as np
import numpy as np

In [ ]:
# crear lista con numeros primos
numeros_primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [ ]:
# crear array a partir de lista
import numpy as np

numeros_primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

array_numeros_primos = np.array(numeros_primos)

print(array_numeros_primos)

[ 2  3  5  7 11 13 17 19 23 29]


In [ ]:
# crear arrays con ceros o cómo inicializar un arreglo de numpy
import numpy as np

array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# crear arrays con números
array_numeros = np.arange(10)
print(array_numeros)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# array con numeros sucesivos
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# haciendo un reshape para dos dimensiones
array_pares=np.arange(0,20,2)

array_pares=array_pares.reshape(2,5)
array_pares

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Punto 2:

In [ ]:
# operaciones aritmeticas sobre np array 1-dimension y 2-dimension
array_impares = array_pares + 1
array_impares

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
# multiplicar por 100
array_impares * 100

array([[ 100,  300,  500,  700,  900],
       [1100, 1300, 1500, 1700, 1900]])

In [ ]:
# resta entre arrays
array_impares - array_pares

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# cuidado con la división entre cero
array_impares / array_pares

/tmp/ipython-input-2135649895.py:2: RuntimeWarning: divide by zero encountered in divide
  array_impares / array_pares


array([[       inf, 1.5       , 1.25      , 1.16666667, 1.125     ],
       [1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556]])

In [ ]:
# métodos asociados a estadística
# suma
suma = np.sum(array_numeros_primos)
print("Suma:", suma)

Suma: 129


In [ ]:
# promedio
promedio = np.mean(array_numeros_primos)
print("Promedio:", promedio)

Promedio: 12.9


In [ ]:
# varianza
varianza = np.var(array_numeros_primos)
print("Varianza:", varianza)

Varianza: 73.28999999999999


In [1]:
# como ordenar un np array
import numpy as np

# Crear un array desordenado
array_desordenado = np.array([17, 3, 11, 29, 5, 2, 23, 13, 7, 19])
print("Array original:", array_desordenado)

Array original: [17  3 11 29  5  2 23 13  7 19]


In [ ]:
# orden ascendente: de menor a mayor
orden_asc = np.sort(array_numeros_primos)
print("Orden ascendente:", orden_asc)

Orden ascendente: [ 2  3  5  7 11 13 17 19 23 29]


In [ ]:
# orden descendente: de mayor a menor
orden_desc = np.sort(array_numeros_primos)[::-1]
print("Orden descendente:", orden_desc)

Orden descendente: [29 23 19 17 13 11  7  5  3  2]


# Punto 3:

In [6]:
# Como seleccionar elements
import numpy as np

array_1d = np.array([10, 20, 30, 40, 50])

# Seleccionar un solo elemento
print("Elemento en posición 0:", array_1d[0])     # 10
print("Elemento en posición 3:", array_1d[3])     # 40

Elemento en posición 0: 10
Elemento en posición 3: 40


In [ ]:
# Seleccionar un elemento
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
# seleccionar el primer elemento
A[0,0]

np.int64(0)

In [ ]:
# seleccionar algún otro elemento
A[1,3]

np.int64(16)

In [ ]:
A[1,2]

np.int64(14)

In [5]:
# Seleccionar varios elementos
import numpy as np

array = np.array([10, 20, 30, 40, 50])

# Seleccionar elementos en posiciones 0, 2 y 4
seleccionados = array[[0, 2, 4]]
print("Elementos en índices 0, 2, 4:", seleccionados)  # [10 30 50]

Elementos en índices 0, 2, 4: [10 30 50]


In [ ]:
# seleccionar por fila
A[1,:]

array([10, 12, 14, 16, 18])

In [ ]:
# seleccionar por columna
A[:,4]

array([ 8, 18])

In [2]:
# Utilizar filter
import numpy as np

array = np.array([5, 12, 19, 23, 30, 3, 18])

# Filtrar menores de 20
menores_20 = array[array < 20]

print("Elementos menores de 20:", menores_20)

Elementos menores de 20: [ 5 12 19  3 18]


In [3]:
# conidicion para menores de 20
import numpy as np

array = np.array([5, 12, 19, 23, 30, 3, 18])

# Condición: menores de 20
menores_20 = array[array < 20]

print("Elementos menores de 20:", menores_20)

Elementos menores de 20: [ 5 12 19  3 18]


In [4]:
# filtrar menores de 20
import numpy as np

array = np.array([5, 12, 19, 23, 30, 3, 18])

# Filtrar menores de 20
menores_20 = array[array < 20]

print("Elementos menores de 20:", menores_20)

Elementos menores de 20: [ 5 12 19  3 18]
